function ymd(date){const y=date.getUTCFullYear();const m=String(date.getUTCMonth()+1).padStart(2,'0');const d=String(date.getUTCDate()).padStart(2,'0');return `${y}${m}${d}`;}
function dateRange(){const start=new Date(Date.UTC(2026,5,11));const end=new Date(Date.UTC(2026,6,20));const out=[];for(let d=new Date(start);d<=end;d.setUTCDate(d.getUTCDate()+1))out.push(ymd(d));return out;}
function scoreMap(event){const comp=event?.competitions?.[0];const scores={};for(const c of comp?.competitors||[]){const abbr=c?.team?.abbreviation;if(abbr)scores[abbr]=Number(c.score??0)}return scores;}
function scorers(event){const comp=event?.competitions?.[0]||{};const details=comp.details||event.details||[];if(!Array.isArray(details))return[];return details.filter(d=>{const t=[d?.type?.text,d?.type?.description,d?.type?.detail,d?.text,d?.shortText,d?.displayText].filter(Boolean).join(' ').toLowerCase();return /goal|own goal|penalty/.test(t)&&!/yellow|red card|substitution|attempt|miss|save/.test(t)}).map(d=>{const minute=d?.clock?.displayValue||d?.displayTime||d?.time||'';const athlete=d?.athletes?.[0]?.displayName||(d?.participants||[]).map(p=>p?.athlete?.displayName||p?.displayName).find(Boolean)||d?.athlete?.displayName||d?.text||d?.shortText||'得点者';const team=d?.team?.abbreviation||d?.team?.shortDisplayName||'';const type=[d?.type?.text,d?.type?.description,d?.text,d?.shortText].filter(Boolean).join(' ').toLowerCase();const tags=[];if(/penalty/.test(type))tags.push('PK');if(/own goal|own-goal/.test(type))tags.push('OG');const suffix=[team,...tags].filter(Boolean).join('／');return `${minute?minute+' ':''}${athlete}${suffix?`（${suffix}）`:''}`}).filter(Boolean)}
function normalize(event){const comp=event?.competitions?.[0]||{};const type=event?.status?.type||{};const text=[type.description,type.detail,type.name].filter(Boolean).join(' ');const completed=!!type.completed||/final|full time|ft|complete/i.test(text);const inProgress=!!type.inProgress||/live|in progress|halftime/i.test(text);const competitors=comp.competitors||[];return{id:String(event.id||''),name:event.name||event.shortName||'',date:event.date||comp.date||'',stage:event.season?.slug||event.group?.name||event.league?.name||'',venue:comp.venue?.fullName||comp.venue?.displayName||'',completed,inProgress,statusText:completed?'終了':inProgress?'試合中':'予定',scores:scoreMap(event),scorers:scorers(event),competitors:competitors.map(c=>({abbr:c?.team?.abbreviation||'',name:c?.team?.displayName||c?.team?.shortDisplayName||'',score:Number(c.score??0)}))}}
async function fetchJson(date){const res=await fetch(`https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/scoreboard?dates=${date}&limit=100`,{headers:{'user-agent':'Mozilla/5.0 worldcup2026'}});if(!res.ok)throw new Error(`ESPN ${date} ${res.status}`);return res.json();}
async function fetchAll(dates){const out=[];for(let i=0;i<dates.length;i+=5){const batch=dates.slice(i,i+5);const settled=await Promise.allSettled(batch.map(fetchJson));out.push(...settled)}return out;}
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'}})}
export async function onRequest(context){try{const dates=dateRange();const results=await fetchAll(dates);const map={};for(const r of results){if(r.status==='fulfilled'&&Array.isArray(r.value?.events)){for(const e of r.value.events){const n=normalize(e);if(n.id)map[n.id]=n}}}return json({ok:true,generatedAt:new Date().toISOString(),events:Object.values(map)})}catch(err){return json({ok:false,error:String(err?.message||err)},502)}}
